name: Test
on:
  push:
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "windows-2022"
          - "windows-2019"
          - "ubuntu-22.04"
          - "macos-12"
          - "macos-11"
        node-version:
          - 16
          - 18
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm test -- --updateSnapshot
      - name: Check that snapshot is saved in correct place
        run: cat lib/__snapshots__/file.js.snap
